version: '3'
services:
  examples:
    build: .
    image: coisa/composer-skeleton
    command: php -S 0.0.0.0:80 -t /app/examples
    ports:
      - 8080:80
    volumes:
      - ./:/app

  doc:
    build: .
    image: coisa/composer-skeleton
    command: composer run doc
    volumes:
      - ./:/app

  tests:
    build: .
    image: coisa/composer-skeleton
    command: composer run tests
    volumes:
      - ./:/app
