name: Laminas CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  laminas-ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
